name: Lint Check 

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main


jobs:
  linting:
    name: linting 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./sqlonfhir"
